import type { Line } from "../../dsl";

/** 00:00-~30:00 - arrivals, agenda, customer signal, model accuracy, capacity. */
export const part1: Line[] = [
  // --- Arrivals ------------------------------------------------------------
  ["maya", "Okay, I think the recording's on. Hi everyone. Let's give people one more minute, I know a couple of folks are coming straight from other calls."],
  ["tom", "Morning. Or, I guess, evening for Elena."],
  ["elena", "It's almost eight here, yes. But I have a very large coffee, so I'm fully present."],
  ["raj", "~Brave."],
  ["marcus", "Can everyone hear me okay? I switched to the headset. My laptop mic was doing the robot voice thing in the design crit yesterday."],
  ["maya", "You sound great, Marcus. Much better than yesterday, honestly."],
  ["marcus", "Ha. Thanks. I'll take it."],
  { pause: 6000 },
  ["daniel", "Hey all, sorry. I was sitting in the old Zoom link by myself for two minutes wondering where everyone was."],
  ["maya", "That's on me, I moved the invite and the old link stayed in the description. Sorry, Daniel."],
  ["daniel", "No worries. I got some email done."],
  ["priya", "I'm here too, I just had my camera off, I'm eating lunch. Hi."],
  ["maya", "Hi Priya. Okay, we're just missing Aisha. She was on with the Globex security team this morning, so I'm guessing that ran long."],
  { pause: 9000 },
  ["aisha", "Hi, sorry, sorry. I'm here. The Globex conversation is actually really relevant to today, so, good timing I guess."],
  ["maya", "Perfect segue. Okay, let me frame this, and then we'll go around."],
  [
    "maya",
    "The goal for this hour is to leave with three things. A locked scope for Insights 2.0. A beta date we actually believe in. And a clear call on SAML SSO versus the Jira integration, because I don't think we can staff both this quarter, and I'd rather we decide that together than have it decided by default.",
    "goals",
  ],
  [
    "maya",
    "Rough agenda. Tom and Aisha on customer signal, maybe ten minutes. Priya on where the clustering model actually is. Marcus has the new dashboard. Then Daniel on integrations and SSO, Elena on launch, and I want to save the last five minutes for owners and dates. Does that sound okay? Anything missing?",
    "agenda",
  ],
  [
    "raj",
    "Can we make sure we talk about capacity before we commit to any dates? I don't want us to walk out of here with a date that assumes the platform team is at a hundred percent, because we're not.",
    "capacity-ask",
  ],
  ["maya", "Yes. Totally fair. Let's do that right after Priya, before the design walkthrough."],
  ["raj", "Great, thanks.", "raj-thanks"],
  ["maya", "Tom, do you want to kick us off?"],

  // --- Customer signal -----------------------------------------------------
  [
    "tom",
    "Sure. So I pulled the last ninety days of churn and downgrade conversations. It's forty-one accounts total. The top reason, by a wide margin, is still some version of 'we have the data but nobody reads it.' Customers export the feedback, it sits in a spreadsheet, and whatever insight is in there never makes it into an actual product decision. That was the stated reason in seventeen of the forty-one.",
    "churn-stat",
  ],
  ["maya", "Seventeen of forty-one. Wow."],
  [
    "tom",
    "Yeah. And that's just the ones who said it out loud. The second cluster is integration gaps. People want the feedback to show up where they already work, so Slack and Jira come up constantly. Eleven accounts mentioned Jira by name.",
    "jira-eleven",
  ],
  ["daniel", "~Eleven, okay. That's higher than what I had in my doc."],
  ["tom", "It's eleven if you count the ones where it came up on a renewal call, not just in a ticket. I can send you the list."],
  ["daniel", "Yes please, that'd be great."],
  [
    "tom",
    "And then the third reason, which is newer, is accuracy of the auto-tagging. A few customers, Brightline was the loudest, have said the tags feel random and they've just stopped trusting them. Olivia over there told me they turned tagging off entirely for their support team.",
    "tagging-trust",
  ],
  ["priya", "Do you know if that's the old keyword tagger or the model we piloted in August?"],
  ["tom", "It's the old one. Brightline wasn't in the pilot."],
  ["priya", "Okay, good. That actually matters a lot, I'll come back to it.", "priya-later"],
  [
    "tom",
    "The good news is the pilot accounts. Eight accounts used the theme clustering prototype. Six of them asked, completely unprompted, when they can have it for real. Sana at Lakeshore Bank said, and I wrote this down, 'this is the first time the tool told me something I didn't already know.'",
    "pilot-quote",
  ],
  ["elena", "Oh, can I steal that quote for the launch?"],
  ["tom", "I'll ask her. I think she'd say yes, she's been a big fan.", "tom-ask-quote"],
  ["marcus", "~That's a great line."],
  ["maya", "It really is. Okay. Aisha, sales side?"],
  [
    "aisha",
    "Yeah. So I'll be blunt. We have two enterprise deals, Globex and Arcadia Health, that are blocked on SAML SSO. Not slowed down, blocked. Their security teams will not sign without it. Together that's about four hundred and twenty thousand in annual contract value.",
    "sso-blocked",
  ],
  ["raj", "~Sorry, four twenty?"],
  [
    "aisha",
    "Four twenty. Globex is about two sixty and Arcadia is about one sixty. And on the Globex call this morning, Victor, their CISO, was really clear. It's SAML plus audit logs, and he wants a date in writing before they'll move to procurement.",
    "globex-ask",
  ],
  ["daniel", "Did he say which identity provider they're on?"],
  ["aisha", "Okta. And Arcadia is on Azure AD. Their IT lead, Imran, brought it up in the first ten minutes of discovery."],
  ["daniel", "Okay. So we'd need both from day one. That's useful to know.", "both-idps"],
  [
    "aisha",
    "And to be fair to the Jira side, Jira comes up in almost every mid-market demo. But nobody has actually walked away from a deal over it. With SSO, people walk away. That's the difference for me.",
    "sso-vs-jira-sales",
  ],
  ["maya", "That's a really useful distinction."],
  ["tom", "~For what it's worth, that matches what I see on retention. For most accounts Jira is a nice-to-have."],
  ["maya", "Tom, of those eleven Jira accounts, how many actually churned, versus just asked for it?"],
  ["tom", "I think two churned. The rest either downgraded or just complained. But I'd want to double check that before anyone quotes it."],
  ["maya", "Okay. Can you confirm that number after the call? It matters for the SSO decision.", "confirm-churn"],
  ["tom", "Yep. I'll confirm the Jira churn number and send it to you and Daniel today.", "tom-churn-commit"],
  ["maya", "Thanks. Anything else on signal before we go to Priya?"],
  [
    "elena",
    "One quick thing, on competitive. Two of the deals we lost last month went to a competitor who's pitching 'AI insights.' I honestly don't think their product is better than ours. But their story is simpler. We keep saying 'feedback analytics,' and I think buyers hear 'another dashboard.'",
    "competitive",
  ],
  ["aisha", "~A hundred percent. I hear that in demos."],
  ["maya", "Noted. Let's come back to that when we get to launch, because I think it connects to Marcus's work too."],

  // --- Model accuracy ------------------------------------------------------
  ["maya", "Okay. Priya, where are we with the model?"],
  ["priya", "Okay, let me share my screen. One sec. Can you all see the eval sheet?"],
  { pause: 7000 },
  ["marcus", "Yep, we can see it."],
  [
    "priya",
    "Great. So, quick recap for anyone who hasn't been following closely. The clustering model takes raw feedback, so support tickets, NPS comments, call notes, app reviews, and groups them into themes. Then it writes a short label and a one-paragraph summary for each theme.",
  ],
  [
    "priya",
    "The August pilot version had a precision of seventy-one percent on our labeled set. Meaning, when it put a comment into a theme, the comment actually belonged there about seven times out of ten.",
    "precision-71",
  ],
  ["raj", "And the target we set for GA was eighty-five, right?"],
  [
    "priya",
    "Eighty-five, yes. With the new embedding model and a re-ranking step I added last sprint, we're at seventy-nine percent on the same set. So real progress, but we're not there yet.",
    "precision-79",
  ],
  ["aisha", "~Sorry, can I ask a dumb question? What does seventy-nine actually feel like for a customer? Is that noticeable?"],
  [
    "priya",
    "Not a dumb question at all. At seventy-nine, if you open a theme with twenty comments in it, maybe four of them look out of place. People notice that. At eighty-five it's about three, and in the pilot interviews that's roughly where people stopped commenting on it.",
    "precision-feel",
  ],
  ["tom", "That tracks with Brightline. With the old tagger they were seeing something like one in three tagged wrong."],
  ["priya", "Right, the old keyword tagger is closer to sixty percent. So even seventy-nine is a big jump from what most customers have today."],
  ["maya", "What gets us from seventy-nine to eighty-five?"],
  [
    "priya",
    "Two things. First, a bigger and better labeled set. Our eval set is only eight hundred comments, and it's skewed toward SaaS companies. I want two thousand, with retail and healthcare properly represented, because that's where it's weakest.",
    "labeled-set",
  ],
  [
    "priya",
    "Second, letting users merge and split themes, and learning from that. Honestly, the merge and split feedback is the biggest lever we have. But it needs design, and it needs the beta to actually generate the data.",
    "path-to-85",
  ],
  ["marcus", "The merge and split interaction is in the new prototype, by the way. I'll show it in a bit."],
  ["priya", "Oh, nice. I didn't know it had made it in.", "priya-nice"],
  [
    "daniel",
    "Priya, one thing I want to flag, for healthcare specifically. If we're sending Arcadia's feedback to a model, their security team is going to ask what happens to patient information in those comments. People put all kinds of things in support tickets.",
    "phi-concern",
  ],
  [
    "priya",
    "Yes. We already redact emails and phone numbers before anything goes to the model. We don't do names or anything like medical record numbers yet. I'd want to add a proper PII redaction pass before any healthcare customer is in the beta.",
    "pii-redaction",
  ],
  ["aisha", "~That will absolutely come up with Arcadia. Their security review is forty pages."],
  ["maya", "Okay. Priya, can you and Daniel scope the redaction pass, so we know what it takes before we invite any healthcare accounts?"],
  ["priya", "Yes. Daniel and I will scope the PII redaction pass this week.", "pii-commit"],
  ["daniel", "Works for me."],
  [
    "raj",
    "Can I ask about latency? Last time I looked, clustering a big workspace was taking, what, forty seconds?",
    "latency-q",
  ],
  [
    "priya",
    "For the largest pilot account, about thirty-eight seconds at p95. For most workspaces it's under ten. The big cost is re-clustering everything every time new feedback comes in. What I'd propose is incremental assignment, where new comments get placed into existing themes right away, and then we only do a full re-cluster nightly.",
    "latency",
  ],
  [
    "raj",
    "That's how I'd want to do it. I really don't want a user staring at a spinner for forty seconds. Can we set a budget? Something like p95 under three seconds for anything the user is actually waiting on.",
    "latency-budget",
  ],
  ["priya", "For incremental assignment, three seconds is doable. For the full re-cluster, no, that has to be a background job."],
  ["raj", "Background job is fine. We have the job queue from the exports work, we can reuse that."],
  [
    "maya",
    "Okay, so the proposal is: incremental assignment in the product, a nightly full re-cluster in the background, and a p95 of three seconds for anything the user waits on. Does anyone object?",
    "latency-decision",
  ],
  ["daniel", "~No, makes sense."],
  ["marcus", "Makes sense to me. It also means I can design for themes updating quietly instead of a big loading state."],
  ["maya", "Great. Priya, can you own getting the labeled set to two thousand?"],
  [
    "priya",
    "Yes. I'll need about three days of labeling help though. I was going to ask Tom's team, because they know how customers actually talk about problems.",
  ],
  ["tom", "We can do that. I can give you two people for the back half of this week."],
  [
    "priya",
    "Perfect. Then I'll run the eval on the two thousand comment set and share the precision report by the middle of next week.",
    "priya-eval-commit",
  ],
  ["maya", "Thank you."],
  { pause: 4000 },

  // --- Capacity --------------------------------------------------------------
  ["maya", "Okay. Raj, you wanted to talk capacity. Go for it."],
  [
    "raj",
    "Yeah. So, just to be honest with everyone. The platform team is five engineers. One of them is on call every week, so realistically it's four. Right now we still have the ingest pipeline hardening from the outage two weeks ago, and that's not optional. That's probably one engineer until the end of the month. So I have three people for new work.",
    "capacity-three",
  ],
  ["maya", "Three people."],
  [
    "raj",
    "Three. And here's roughly how I see it. Incremental assignment plus the background re-cluster is maybe one and a half people for three weeks. SAML SSO done properly, meaning Okta and Azure AD, audit logs, SCIM later, is two people for four to five weeks. And the Jira integration is two people for about four weeks, because their API is, uh, a lot.",
    "estimates",
  ],
  ["aisha", "~It really is a lot."],
  ["daniel", "~It's a lot."],
  [
    "raj",
    "So I can do Insights 2.0 plus one of SSO or Jira. Not both. Not this quarter, not with three people, unless we want to cut corners on the outage work, and I really don't.",
    "not-both",
  ],
  ["daniel", "What if we did a much lighter Jira thing? Like, just a 'create issue' button, one way, no sync at all?"],
  ["raj", "That's a lot smaller. Maybe a week and a half. But I'd still be taking that week and a half from somewhere."],
  ["maya", "Could we borrow anyone from the growth team for a few weeks?"],
  [
    "raj",
    "I asked. They're mid-way through the billing migration, and I don't think pulling someone off billing is a good idea. That's the kind of thing that goes badly if you rush it.",
  ],
  ["maya", "Fair. No, let's not touch billing."],
  [
    "maya",
    "Okay, let's hold the SSO and Jira question for a few minutes, because I want Daniel to walk through it properly with the full picture. Marcus, let's see the dashboard first.",
    "hold-sso",
  ],
];
