import { defineMeeting } from "../dsl";
import { D, staff } from "../workspace";

/** Three days after the ingest outage. */
export const postmortem = defineMeeting({
  key: "postmortem-ingest-delay",
  title: "Postmortem: ingest delay",
  meetingType: "general",
  defaultTemplate: "general",
  platform: "google_meet",
  owner: D("raj"),
  startedAt: "D-13@15:00",
  scheduledMin: 30,
  participants: {
    raj: staff("raj"),
    sam: staff("sam"),
    lena: staff("lena"),
    priya: staff("priya"),
    tom: staff("tom"),
    maya: staff("maya"),
  },
  script: [
    [
      "raj",
      "Okay, let's start. Quick reminder that this is a blameless postmortem. We're here to understand how the system let this happen, not who did what. Sam, can you walk us through the timeline?",
      "raj-blameless",
    ],
    [
      "sam",
      "Sure. At nine twelve in the morning, Eastern, a schema migration started on the events table. It was adding an index. It took a lock that blocked writes. From that point, the ingest workers couldn't write, so everything piled up in the queue.",
      "sam-timeline",
    ],
    [
      "sam",
      "Nothing errored. The workers were just waiting. So none of our alerts fired. At one forty in the afternoon, Brightline emailed support saying no new feedback had shown up since the morning. That's when we noticed.",
      "sam-detection",
    ],
    ["maya", "~So about four and a half hours before we knew."],
    ["sam", "Right. We killed the migration at one fifty-two, the lock released, and the queue drained by about three fifteen. Total delay was around six hours for the worst affected workspaces."],
    ["tom", "Two hundred and twelve workspaces affected. We got fourteen tickets and two escalations, one of them Brightline."],
    ["raj", "What went well?"],
    [
      "lena",
      "We didn't lose any data. The queue held everything, and once the lock released, the workers caught up on their own. That's the durable queue doing exactly its job.",
      "lena-well",
    ],
    ["priya", "~And the clustering jobs recovered automatically once the data landed."],
    ["raj", "What went badly?"],
    [
      "lena",
      "Three things. We ran a blocking migration during peak hours. Our alerting only looks at errors, not at how far behind we are. And there was no runbook for 'ingest is stuck', so it took a while to find the lock.",
      "lena-badly",
    ],
    [
      "tom",
      "And from the customer side, we had no template for this kind of incident. My team wrote fourteen slightly different replies. Brightline got a vague answer first, which didn't help, given they're already unhappy with us.",
      "tom-comms",
    ],
    ["raj", "Okay. Action items. Let's make them specific and owned."],
    ["sam", "I'll build a queue lag alert that pages on-call when ingest is more than five minutes behind.", "sam-alert"],
    ["lena", "I'll evaluate online migration tools, so schema changes don't lock hot tables.", "lena-online"],
    [
      "raj",
      "And I'll write a policy. No blocking schema changes on hot tables during business hours without a review. Plus a runbook for stuck ingest.",
      "raj-policy",
    ],
    ["tom", "I'll write an incident communication template for customer-facing incidents, so we respond consistently.", "tom-template"],
    [
      "maya",
      "One more from me. Brightline should get a personal follow-up, not just the template. Tom, can you and I call Olivia?",
      "maya-brightline",
    ],
    ["tom", "Yes, I'll set up a call with Olivia for next week.", "tom-brightline"],
    ["raj", "Great. I'll write this up and share the postmortem doc. Thanks everyone, this was really constructive."],
  ],
  actionItems: [
    { text: "Build a queue lag alert that pages on-call when ingest is > 5 minutes behind", owner: "sam", at: "sam-alert", quote: "I'll build a queue lag alert that pages on-call", status: "done" },
    { text: "Evaluate online migration tools so schema changes can't lock hot tables", owner: "lena", at: "lena-online", quote: "I'll evaluate online migration tools", status: "done" },
    { text: "Write a policy for schema changes on hot tables, plus a stuck-ingest runbook", owner: "raj", at: "raj-policy", quote: "I'll write a policy", status: "done" },
    { text: "Create an incident communication template for customer-facing incidents", owner: "tom", at: "tom-template", quote: "I'll write an incident communication template", status: "done" },
    { text: "Set up a personal follow-up call with Olivia at Brightline", owner: "tom", at: "tom-brightline", quote: "I'll set up a call with Olivia for next week", due: "D-10", status: "done" },
  ],
  highlights: [
    { at: "sam-detection", label: "Found out from a customer, 4.5 hours in" },
    { at: "lena-well", label: "No data lost: the durable queue held" },
  ],
  clips: [{ slug: "postmortem-timeline", title: "Outage timeline in 90 seconds", from: "sam-timeline", to: "sam-detection", views: 31, by: "raj" }],
  knowledge: {
    overview: "Blameless postmortem of the ingest delay: a blocking index migration during peak hours stalled ingest ~6 hours for 212 workspaces. No data was lost, but detection took 4.5 hours because alerts only watched errors. Five owned follow-ups.",
    topics: [
      { title: "Timeline", summary: "Migration lock at 9:12; customer report at 1:40pm; migration killed at 1:52; queue drained by 3:15.", from: "sam-timeline", to: "sam-detection" },
      { title: "What went well", summary: "The durable queue kept all data; downstream jobs self-recovered.", from: "lena-well", to: "lena-well" },
      { title: "What went badly", summary: "Peak-hours blocking migration, error-only alerting, no runbook, inconsistent customer comms.", from: "lena-badly", to: "tom-comms" },
      { title: "Follow-ups", summary: "Queue lag alert, online migrations, migration policy and runbook, comms template, Brightline call.", from: "sam-alert", to: "tom-brightline" },
    ],
    decisions: [["No blocking schema changes on hot tables during business hours without review.", "raj-policy"]],
    openQuestions: [],
    speakerContributions: {
      raj: "Facilitated; owns the policy and runbook.",
      sam: "Walked the timeline; owns the queue lag alert.",
      lena: "What went well and badly; owns the online migration evaluation.",
      tom: "Customer impact; owns the comms template.",
      maya: "Asked for a personal Brightline follow-up.",
      priya: "Confirmed clustering recovered.",
    },
  },
});

/** The day before the alignment call - Marcus's headset trouble is referenced there. */
export const designCrit = defineMeeting({
  key: "design-crit-dashboard-v3",
  title: "Design crit: Insights dashboard v3",
  meetingType: "product_review",
  defaultTemplate: "general",
  platform: "google_meet",
  owner: D("marcus"),
  startedAt: "D-3@16:00",
  scheduledMin: 30,
  participants: { marcus: staff("marcus"), maya: staff("maya"), raj: staff("raj"), elena: staff("elena") },
  script: [
    ["marcus", "Okay, thanks for coming. This is dashboard v3. The big proposal is making Themes the default home instead of the feed. I want honest reactions."],
    [
      "marcus",
      "Each theme card shows the label, a count, a trend arrow, and five representative quotes. The idea is you can understand the theme without clicking in.",
      "marcus-card",
    ],
    ["maya", "Marcus, sorry, you're breaking up a bit. You sound like a robot."],
    ["marcus", "Is this better? I'll switch to my phone's mic."],
    { pause: 8000 },
    ["marcus", "Okay, how about now?"],
    ["elena", "Much better."],
    ["marcus", "Great. New headset arrives tomorrow, I promise. So, reactions to the cards?"],
    [
      "maya",
      "I like the direction a lot. My worry is five quotes. It's a wall of text on every card. I'd guess people read one or two and skip the rest.",
      "maya-quotes",
    ],
    [
      "marcus",
      "Fair. I can run a quick hallway test before the alignment meeting, three quotes versus five, with a handful of people from CS.",
      "marcus-test",
    ],
    [
      "elena",
      "The trend arrow. It's red when a theme is growing. But not every growing theme is bad. If people are praising the new export feature more and more, that's growth, and it's good news. Red makes it look like an alarm.",
      "elena-arrow",
    ],
    ["marcus", "~Oh, that's a really good point. We baked in the assumption that feedback is complaints."],
    [
      "marcus",
      "What if the arrow is neutral, just direction and size, and we add a small sentiment indicator next to the label? Then growth and sentiment are separate signals.",
      "marcus-sentiment",
    ],
    ["maya", "I like that. It's more honest."],
    [
      "raj",
      "On merge and split. It's drag and drop right now. How does anyone discover that? I didn't notice it until you told me.",
      "raj-discover",
    ],
    [
      "marcus",
      "Yeah, discoverability is weak. I'll add explicit merge and split buttons in the theme detail, and keep drag and drop as the power user shortcut.",
      "marcus-buttons",
    ],
    [
      "maya",
      "Big picture question. Are we all comfortable taking Themes as default into the alignment meeting as the proposal? I'd like design to present it there.",
      "maya-proposal",
    ],
    ["raj", "Yes. I think it's the right call."],
    ["elena", "~Yes. It's the story we want to tell, too."],
    ["marcus", "Great. I'll update the prototype with neutral arrows, sentiment, and the buttons, and present it at the alignment meeting.", "marcus-update"],
  ],
  actionItems: [
    { text: "Hallway test: 3 vs 5 quotes per theme card with CS teammates", owner: "marcus", at: "marcus-test", quote: "I can run a quick hallway test before the alignment meeting", due: "D-2", status: "done" },
    { text: "Update prototype: neutral trend arrows, sentiment indicator, explicit merge/split buttons", owner: "marcus", at: "marcus-update", quote: "I'll update the prototype with neutral arrows, sentiment, and the buttons", due: "D-2", status: "done" },
  ],
  highlights: [{ at: "elena-arrow", label: "Growth isn't always bad: red arrow problem" }],
  clips: [{ slug: "red-arrow-problem", title: "Why a red growth arrow is misleading", from: "elena-arrow", to: "marcus-sentiment", views: 11, by: "marcus" }],
  knowledge: {
    overview: "Design crit of dashboard v3 with Themes as the default home. The team agreed to take Themes-first to the alignment meeting, to test fewer quotes per card, to separate trend direction from sentiment, and to make merge/split discoverable with explicit buttons.",
    topics: [
      { title: "Theme cards", summary: "Five quotes feels like a wall of text; hallway test of 3 vs 5.", from: "marcus-card", to: "marcus-test" },
      { title: "Trend arrow", summary: "Red implies bad, but praise can grow too; neutral arrow plus separate sentiment indicator.", from: "elena-arrow", to: "marcus-sentiment" },
      { title: "Merge/split discoverability", summary: "Drag-and-drop only was invisible; add explicit buttons.", from: "raj-discover", to: "marcus-buttons" },
      { title: "Proposal", summary: "Themes-first goes to the alignment meeting, presented by design.", from: "maya-proposal", to: "marcus-update" },
    ],
    decisions: [
      ["Trend arrows become neutral; sentiment shown separately.", "marcus-sentiment"],
      ["Themes-as-default goes to the alignment meeting as the proposal.", "maya-proposal"],
    ],
    openQuestions: [["Three or five quotes per card? Hallway test pending.", "marcus-test"]],
    speakerContributions: {
      marcus: "Presented v3; owns the prototype updates and test.",
      maya: "Flagged quote density; framed the proposal.",
      elena: "Spotted the red-arrow bias.",
      raj: "Raised merge/split discoverability.",
    },
  },
  summaries: {
    product_review: {
      goals: [["Make the home screen answer 'what are customers telling us' without clicking in.", "marcus-card"]],
      customer_signal: ["No new customer data; this was an internal crit."],
      decisions: [
        ["Neutral trend arrows plus a separate sentiment indicator.", "marcus-sentiment"],
        ["Take Themes-as-default to the alignment meeting.", "maya-proposal"],
      ],
      scope: [["Add explicit merge/split buttons; keep drag-and-drop as a shortcut.", "marcus-buttons"]],
      risks: [["Cards overloaded with quotes may go unread.", "maya-quotes"], ["Red arrows could make good news look like alarms.", "elena-arrow"]],
      launch_plan: ["Not discussed."],
      open_questions: [["3 vs 5 quotes per card, pending the hallway test.", "marcus-test"]],
    },
  },
});

export const launchPlanning = defineMeeting({
  key: "launch-planning-insights",
  title: "Insights 2.0 launch planning",
  meetingType: "general",
  defaultTemplate: "general",
  platform: "google_meet",
  owner: D("elena"),
  startedAt: "D-4@16:00",
  scheduledMin: 30,
  participants: {
    elena: staff("elena"),
    maya: staff("maya"),
    tom: staff("tom"),
    ivy: { name: "Ivy Brooks", email: "ivy@brookscontent.example", title: "Content Strategist (contractor)", company: "Brooks Content Co.", external: true },
  },
  script: [
    ["elena", "Thanks everyone. Ivy, welcome, great to have you on this. The goal today is a draft launch plan I can bring to the alignment meeting. Nothing is final."],
    [
      "elena",
      "My starting point: I don't think we should do one big launch. The model isn't at the quality bar yet. I'd rather do a quiet private beta with design partners, and save the big moment for general availability.",
      "elena-two-phase",
    ],
    [
      "maya",
      "I agree with that instinct. A big launch with themes that are wrong a fifth of the time would be a bad first impression, and first impressions of AI features stick.",
      "maya-agree",
    ],
    [
      "tom",
      "From CS, a beta works well if it's a real program. Regular check-ins, a shared channel, clear expectations. Otherwise people sign up and never log in.",
      "tom-program",
    ],
    ["elena", "How many partners could your team realistically support?"],
    ["tom", "Around twenty. More than that and we can't talk to everyone weekly."],
    [
      "ivy",
      "For GA, I'd build the launch around customer stories rather than features. If we can get three strong stories from the beta, that's the backbone of the blog post, the webinar, and the sales deck.",
      "ivy-stories",
    ],
    ["elena", "Tom, who could those stories come from?"],
    [
      "tom",
      "Lakeshore Bank for sure. Their pilot feedback was glowing. Probably a retail account too, and ideally a mid-market logistics or operations company. Aisha has a good prospect there.",
      "tom-candidates",
    ],
    [
      "ivy",
      "I'll draft a content calendar that works backwards from GA. Beta invite, a couple of teaser posts, stories, then the launch week.",
      "ivy-calendar",
    ],
    [
      "maya",
      "One caution. Don't put a GA date in anything public yet. GA depends on the precision number, and I don't want us committed to a date the model can't hit.",
      "maya-caution",
    ],
    ["elena", "~Understood. Everything relative to GA, no dates."],
    [
      "elena",
      "Okay, so the proposal for the alignment meeting is: private beta with about twenty design partners, run as a real program, and a story-led GA launch with no public date until precision is there.",
      "elena-proposal",
    ],
    ["maya", "Yes. Bring that. I'll make sure you have a slot."],
    ["elena", "I'll finalize the one-page plan before the alignment meeting.", "elena-finalize"],
    ["tom", "And I'll start a list of story candidates.", "tom-list"],
  ],
  actionItems: [
    { text: "Finalize the one-page launch plan for the alignment meeting", owner: "elena", at: "elena-finalize", quote: "I'll finalize the one-page plan before the alignment meeting", due: "D-2", status: "done" },
    { text: "Draft a content calendar working backwards from GA (no public dates)", owner: "ivy", at: "ivy-calendar", quote: "I'll draft a content calendar that works backwards from GA", due: "D+3" },
    { text: "Start a list of customer story candidates", owner: "tom", at: "tom-list", quote: "I'll start a list of story candidates" },
  ],
  highlights: [{ at: "maya-caution", label: "No public GA date until precision is there" }],
  knowledge: {
    overview: "Draft launch strategy for Insights 2.0: a two-phase launch with a private beta for ~20 design partners run as a real program, then a story-led GA with no public date until the precision bar is met.",
    topics: [
      { title: "Two-phase launch", summary: "Quiet private beta, big launch at GA, because model quality isn't at the bar yet.", from: "elena-two-phase", to: "maya-agree" },
      { title: "Design partner program", summary: "About 20 partners, weekly check-ins and a shared channel.", from: "tom-program", to: "tom-program" },
      { title: "Story-led GA", summary: "Three customer stories as the backbone; candidates Lakeshore Bank, retail, logistics.", from: "ivy-stories", to: "ivy-calendar" },
      { title: "No public dates", summary: "GA depends on precision; content stays relative to GA.", from: "maya-caution", to: "elena-proposal" },
    ],
    decisions: [["Propose a two-phase launch (private beta, then story-led GA) at the alignment meeting.", "elena-proposal"], ["No public GA date until precision is met.", "maya-caution"]],
    openQuestions: [["Which retail and logistics accounts will commit to stories?", "tom-candidates"]],
    speakerContributions: {
      elena: "Proposed the two-phase launch.",
      maya: "Endorsed it; no public GA date.",
      tom: "Defined the program shape and story candidates.",
      ivy: "Story-led GA and content calendar.",
    },
  },
});
