import type { Line } from "../dsl";

/** Fifth pass: sized at ~1.8x each remaining shortfall, since earlier passes kept landing short. */
export const round5Scenes: Record<string, Record<string, Line[]>> = {
  "pricing-ai-usage-caps": {
    "aisha-test": [
      ["maya", "Which two will you start with?"],
      ["aisha", "Kestrel first, because Grace already told us what she hates about per-seat pricing. Then Juniper, because they're the most price-sensitive prospect we have. If the shape works for both of them, it'll work for most."],
    ],
  },
  "globex-security-review": {
    "aisha-date": [["victor", "That's reasonable. I'd rather wait a week for a real date than get a guess today."]],
  },
  "design-crit-dashboard-v3": {
    "maya-quotes": [
      ["raj", "Would fewer quotes also make the page faster? Every card loads its quotes separately right now."],
      [
        "marcus",
        "Yes, probably noticeably. Five quotes across twenty cards is a hundred requests on page load. Three would help, and we could load the quotes in one batch instead of per card.",
        "marcus-perf",
      ],
      ["raj", "~One batch, please. I'll make a note for Sam."],
    ],
  },
  "interview-backend-jordan": {
    "jordan-slo": [
      ["priya", "What would you put on the team's dashboard, if you could only pick three charts?"],
      [
        "jordan",
        "Queue lag over time, the SLO burn rate, and the dead letter queue size. Those three tell you whether data is flowing, whether you're keeping your promise to customers, and whether something is silently failing.",
        "jordan-three-charts",
      ],
      ["raj", "~That's a better dashboard than the one we have now, honestly."],
      ["jordan", "Everyone's dashboard has thirty charts. The three that matter get lost in the other twenty-seven."],
    ],
  },
  "launch-planning-insights": {
    "elena-two-phase": [
      ["tom", "How long would the beta run before GA, roughly? I need to plan my team's time."],
      [
        "elena",
        "It depends on the model, but I'd plan for six to eight weeks. If the accuracy gets there faster, great. If it takes longer, we extend the beta rather than rush GA.",
        "elena-duration",
      ],
      ["tom", "Six to eight weeks with twenty partners is a lot of check-ins, but it's doable if we stagger them across the week."],
      ["maya", "~And Andre starts soon, which helps with capacity."],
    ],
  },
  "1on1-maya-raj": {
    "maya-praise": [["raj", "Honestly, a lot of the credit goes to Lena. She wrote most of the timeline section, and it's the clearest part of the document."]],
  },
  "1on1-maya-daniel": {
    "daniel-button": [
      ["daniel", "Should the button be available to everyone, or only admins?"],
      [
        "maya",
        "Everyone who can see the theme. The whole point is to lower the friction between spotting a problem and getting it to the team that can fix it. If admins have to do it, it'll pile up.",
        "maya-button-access",
      ],
      ["daniel", "Makes sense. I'll put that in the recommendation."],
    ],
  },
  "leadership-sync-weekly": {
    "maya-hire-ask": [
      ["chris", "How long does it usually take us to hire a staff engineer?"],
      [
        "raj",
        "About three months from opening the role to someone starting, based on the last two. The market's a bit better now, so maybe faster. We have one strong candidate from a referral already, who could move quickly.",
        "raj-hire-time",
      ],
      ["helen", "~Three months is a long time to carry the on-call load."],
      ["raj", "It is, which is why the tuning work on alerts matters in the meantime. We can cut the noise while we hire."],
    ],
    "tom-nrr": [
      ["helen", "What was the plan number for NRR this quarter?"],
      [
        "tom",
        "A hundred and three. So we're six points behind. Some of that will come back when Harbor and Pine's usage recovers, but not all of it.",
        "tom-plan-gap",
      ],
      ["chris", "~Six points is significant. Let's review it again at the end of the month."],
    ],
  },
  "interview-designer-sofia": {
    "@start": [
      ["marcus", "Hi Sofia, welcome. Can you hear us okay?"],
      ["sofia", "Yes, perfectly. Hi Marcus, hi Maya. Thanks for having me."],
      ["maya", "Thanks for coming in. We've been looking forward to this. Marcus has been talking about your portfolio all week."],
      ["sofia", "~Oh no, now I'm nervous. In a good way."],
    ],
    "sofia-labels": [
      ["maya", "How would you test label wording? It's generated by the model, so it changes all the time."],
      [
        "sofia",
        "I'd pick twenty real themes, write three versions of each label, the model's, a shorter one, and a problem-focused one, and ask people which one they'd act on. Then feed the winning style back into the prompt as examples.",
        "sofia-label-test",
      ],
      ["marcus", "~That's basically what Priya and I were planning, but more rigorous."],
    ],
  },
  "1on1-maya-elena": {
    "maya-feedback": [
      ["maya", "Could you share the next draft as a one-pager first, before the full version? Then I can give direction early, before you've put in all the work."],
      [
        "elena",
        "Yes, that's a good idea. It would also save me from polishing sections that end up being cut.",
        "elena-one-pager-first",
      ],
      ["maya", "Exactly. Direction first, polish later."],
      ["elena", "~I'll try it with the Insights positioning next week."],
    ],
  },
  "kestrel-discovery": {
    "noah-trial": [["grace", "What will you need from Ben to set that up? Just the API token?"], ["noah", "Just the token with read access. Ben, I'll send you the exact permissions so you can create it safely."], ["ben", "~Perfect, that's easy."]],
  },
  "brightline-checkin": {
    "olivia-tagging": [
      ["maya", "When did you first notice the tags getting worse? Was it gradual or sudden?"],
      [
        "olivia",
        "Gradual. About six months ago we launched a new returns process, and the tags just never caught up. Everything about returns ended up as 'shipping', because the words overlap. It got worse every month after that.",
        "olivia-returns",
      ],
      ["tom", "~That's a really useful clue for the audit. The rules probably predate the returns process."],
    ],
    "maya-invite": [
      ["olivia", "Would we have to share our data with other design partners, or anything like that?"],
      [
        "maya",
        "No, never. Your data stays in your workspace. What we learn is how people use the product, like which themes they merge or split. Never the content of your feedback with anyone else.",
        "maya-data-private",
      ],
      ["olivia", "Good. That would have been a deal breaker for our legal team."],
    ],
  },
  "interview-csm-andre": {
    "andre-sales": [
      ["tom", "Last question from me. What's a mistake you made as a CSM, and what did you learn?"],
      [
        "andre",
        "Early on, I only had one contact at a big account. She left, and I found out when the renewal wasn't signed. We lost it. Since then, I never have fewer than two relationships in any account, even small ones.",
        "andre-mistake",
      ],
      ["tom", "~That's a lesson most of us learn the hard way."],
    ],
  },
  "juniper-intro": {
    "hiro-jira": [
      ["aisha", "Who else on your team would use the product?"],
      ["hiro", "My two support leads, and probably our head of product. She's the one who'd really benefit from seeing what customers are saying without waiting for me to summarize it."],
      ["aisha", "~That's a great use case. Product teams are often the biggest fans."],
    ],
  },
  "arcadia-discovery": {
    "rosa-win": [
      ["aisha", "Would a pilot on one hospital make sense, rather than all eleven?"],
      [
        "rosa",
        "Yes, that's how we'd want to do it. One hospital, two or three months, then expand if the results are there. Our largest site would be the natural choice, it has the most feedback.",
        "rosa-pilot",
      ],
    ],
  },
  "postmortem-ingest-delay": {
    "raj-blameless": [
      ["maya", "Before we start, can I say thank you to everyone who worked late that day. I know it was stressful."],
      ["raj", "~Thanks Maya. It was a long afternoon for a few people here."],
    ],
    "sam-alert": [["raj", "Five minutes feels right. Too low and it pages for normal spikes, too high and we're back to finding out from customers."]],
  },
};
